# Generated by Django 5.2.7 on 2025-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupregistration',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signupregistration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='signupregistration',
            name='username',
        ),
        migrations.AlterField(
            model_name='signupregistration',
            name='gender',
            field=models.CharField(default='', max_length=12),
        ),
    ]
